### ISSUE TITLE
A boolean transformer

### ISSUE THREAD

**Issue by njmmatthieu** [oncodash/ontoweaver#122]
Hello, 
It would be very useful to have a transformer that outputs a boolean and transforms a value that the user gives as bool:True and another one as bool:False. 
For example:
```
- boolean:
    column: column_name
    to_object: column_name
    via_relation: blablabla
    true: 1
    false: 0
```
Thank you, 
Matthieu
