### ISSUE TITLE
Clarify in the readme that the keywords of the transformer should be defined before the `match` clause, if branching is used.

### ISSUE THREAD

**Issue by mbaric758** [oncodash/ontoweaver#142]
Case where error encountered:
 
    - map:
        if_from_column: target
        match_type_from_column: type
        match:
            - post_translational:
                to_object: target_proetin
                final_type: p
                via_relation: p_t

**Comment by njmmatthieu** [comment]
In fact, we encounter some cases where we need to have "final_type" inside the match clause.
Example:
Source - Target - InteractionType
ProtA - ProtC - PostTranslational
ProtB - ProtC - Transcriptional
DrugA - ProtC - SmallMoleculeProtein

Here I would like to do:
```
row:
    map:
        id_from_column: Source
        match_type_from_column: InteractionType
        match:
        - ^(?!SmallMoleculeProtein$).*: 
            to_subject: source_protein
            final_type: protein
        - SmallMoleculeProtein:
            to_subject: protein
```

But then an error is raised: 

```
raise ValueError(f"Merged value `{lhs}`/`{rhs}` not identical to previously seen one: `{self.merged}`.")
ValueError: Merged value `drug`/`protein` not identical to previously seen one: `drug`.
```
