### ISSUE TITLE
to_property mappings not appearing in neo4j (v5)

### ISSUE THREAD

**Issue by mbaric758** [oncodash/ontoweaver#2]
When trying to map information as a property of a node, for example:

```
    strand:
        to_property:
            strand:
                -variant
```

 the mapping of the property does not seem to exist in the neo4j visualisation of the node.
